### ISSUE TITLE
FaustDSP : 82 : ERROR : undefined symbol : peaking

### ISSUE THREAD

**Issue by darkoverlordofdata** [micbuffa/FaustPowerAmp#1]
I get an error when I try to run this in FauseIDE. 
If I modify 'feedbackCircuit = presence:*(gainNFL) ' to remove rhe presence variable, it compiles, and sounds pretty nice!

Is 'peaking' an obsolete member on the webaudio api or is this your own customization?

**Comment by darkoverlordofdata** [comment]
It appears the faust api has changed: [https://faustlibraries.grame.fr/libs/webaudio/#wapeaking2](https://faustlibraries.grame.fr/libs/webaudio/#wapeaking2),  when I change it fromwapeaking to wapeaking2, it now works.

byw - still sounds great!

**Comment by micbuffa** [comment]
Argl. The FAUST IDE still requires peaking and not "peaking2". I'll wait until it is supported also by the FAUST IDE before pushing the change peaking -> peaking2. I will ask FAUST people about this....
